### PR TITLE
fix: upgraded Lombok so project can be build on Java 17

### PR DESCRIPTION
**Pull request by johanjanssen**

### CODE REVIEW

**Comment by D-D-H** [comment]
Hi,
The ECA check still failed.

**Comment by autumnfound** [comment]
@johanjanssen it looks like the problem is in your local Git configs. Your email is quoted for some reason, which is not how that field is typically used. Comparing the last 3 commits on your branch can give some additional context:

```
Commit: 7638a60, Committer: ¨johanjanssen2001@gmail.com¨, Author: ¨johanjanssen2001@gmail.com¨
Commit: 262a4e8, Committer: denghui.ddh@alibaba-inc.com, Author: denghui.ddh@alibaba-inc.com
Commit: b53f16d, Committer: denghui.ddh@alibaba-inc.com, Author: denghui.ddh@alibaba-inc.com
```

If you update your git config emails and use `git commit --amend --reset-author` you should be able to update your commit and fix the bad email entries. You can then force push to your fork and it should be resolved. You can validate by using the following command, which will show you the committer and author email fields for the HEAD commit.

```
git show -s --format='Commit: %h, Committer: %ce, Author: %ae'
```

**Comment by johanjanssen** [comment]
@autumnfound thanks a lot for your help! I looked at my git log before, but somehow missed the quotes :(. Removed them now and the ECA check passes. Thanks again!

**Comment by autumnfound** [comment]
> @autumnfound thanks a lot for your help! I looked at my git log before, but somehow missed the quotes :(. Removed them now and the ECA check passes. Thanks again!

A lot of platforms quote stuff, so it's not always super obvious! Glad we could resolve this

**Comment by D-D-H** [comment]
Thank you.

**Pull request merged**
