### PR TITLE
fix: should use getQName when reading rule attributes

### PR DESCRIPTION
**Pull request by qiuchenjian**
[Solve issue 49](https://github.com/adoptium/emt4j/issues/49)

### CODE REVIEW

**Comment by D-D-H** [comment]
The content looks good to me.

Could you modify the title to something like 'fix: should use getQName when reading rule attributes'? The problem is not caused by the JDK version.

**Comment by D-D-H** [comment]
And you need to sign the eca.

https://api.eclipse.org/git/eca/status/gh/adoptium/emt4j/51

**Comment by qiuchenjian** [comment]
I have signed the eca and register the eclipse account， but it still prompts user does not exist

image

image

**Comment by qiuchenjian** [comment]
image

**Comment by D-D-H** [comment]
Did you sign the eca using the email `807169000@qq.com`?

**Comment by qiuchenjian** [comment]
> Did you sign the eca using the email `807169000@qq.com`?

image

**Comment by D-D-H** [comment]
Did you receive the confirmation email from Eclipse? There should be a verify link in it.

**Comment by qiuchenjian** [comment]
> Did you receive the confirmation email from Eclipse? There should be a verify link in it.

I confirm the email when i register the eclipse account, then sign in 。

but i didn't receive any email when i sign in the eca,  as the pic of above, i have sign eca succ and become contributor aggrement status.

**Comment by D-D-H** [comment]
Passed.

**Review by D-D-H — APPROVED** [review]

**Comment by D-D-H** [comment]
Merged. 

@qiuchenjian Thanks for the contribution.

**Pull request merged**
